
// DO NOT EDIT: AUTOGENERATED FILE (by assets/gennerators/textures.embed.py, called from CMakeLists.txt)
#pragma once

#include <gccore.h>

extern const u8 mainTextureData[] ATTRIBUTE_ALIGN(32);
extern const u32 mainTextureSize;
extern const u8 nightTextureData[] ATTRIBUTE_ALIGN(32);
extern const u32 nightTextureSize;
extern const GXColor dayLight[] ATTRIBUTE_ALIGN(32);
extern const GXColor nightLight[] ATTRIBUTE_ALIGN(32);
inline constexpr u16 CUBEMAP_NIGHT_T_X = 0;
inline constexpr u16 CUBEMAP_NIGHT_T_Y = 0;
inline constexpr u16 CUBEMAP_NIGHT_T_SZ = 768;

inline constexpr u16 CUBEMAP_NIGHT_B_X = 0;
inline constexpr u16 CUBEMAP_NIGHT_B_Y = 0;
inline constexpr u16 CUBEMAP_NIGHT_B_SZ = 768;

inline constexpr u16 CUBEMAP_NIGHT_N_X = 0;
inline constexpr u16 CUBEMAP_NIGHT_N_Y = 0;
inline constexpr u16 CUBEMAP_NIGHT_N_SZ = 768;

inline constexpr u16 CUBEMAP_NIGHT_S_X = 0;
inline constexpr u16 CUBEMAP_NIGHT_S_Y = 0;
inline constexpr u16 CUBEMAP_NIGHT_S_SZ = 768;

inline constexpr u16 CUBEMAP_NIGHT_W_X = 0;
inline constexpr u16 CUBEMAP_NIGHT_W_Y = 0;
inline constexpr u16 CUBEMAP_NIGHT_W_SZ = 768;

inline constexpr u16 CUBEMAP_NIGHT_E_X = 0;
inline constexpr u16 CUBEMAP_NIGHT_E_Y = 0;
inline constexpr u16 CUBEMAP_NIGHT_E_SZ = 768;

inline constexpr u16 CUBEMAP_DAY_N_X = 480;
inline constexpr u16 CUBEMAP_DAY_N_Y = 480;
inline constexpr u16 CUBEMAP_DAY_N_SZ = 32;

inline constexpr u16 CUBEMAP_DAY_S_X = 480;
inline constexpr u16 CUBEMAP_DAY_S_Y = 480;
inline constexpr u16 CUBEMAP_DAY_S_SZ = 32;

inline constexpr u16 CUBEMAP_DAY_W_X = 480;
inline constexpr u16 CUBEMAP_DAY_W_Y = 480;
inline constexpr u16 CUBEMAP_DAY_W_SZ = 32;

inline constexpr u16 CUBEMAP_DAY_E_X = 480;
inline constexpr u16 CUBEMAP_DAY_E_Y = 480;
inline constexpr u16 CUBEMAP_DAY_E_SZ = 32;

inline constexpr u16 CUBEMAP_DAY_T_X = 496;
inline constexpr u16 CUBEMAP_DAY_T_Y = 482;
inline constexpr u16 CUBEMAP_DAY_T_SZ = 1;

inline constexpr u16 CUBEMAP_DAY_B_X = 496;
inline constexpr u16 CUBEMAP_DAY_B_Y = 510;
inline constexpr u16 CUBEMAP_DAY_B_SZ = 1;

inline constexpr u16 CUBEMAP_SUNRISE_N_X = 448;
inline constexpr u16 CUBEMAP_SUNRISE_N_Y = 480;
inline constexpr u16 CUBEMAP_SUNRISE_N_SZ = 32;

inline constexpr u16 CUBEMAP_SUNRISE_S_X = 448;
inline constexpr u16 CUBEMAP_SUNRISE_S_Y = 480;
inline constexpr u16 CUBEMAP_SUNRISE_S_SZ = 32;

inline constexpr u16 CUBEMAP_SUNRISE_W_X = 448;
inline constexpr u16 CUBEMAP_SUNRISE_W_Y = 480;
inline constexpr u16 CUBEMAP_SUNRISE_W_SZ = 32;

inline constexpr u16 CUBEMAP_SUNRISE_E_X = 448;
inline constexpr u16 CUBEMAP_SUNRISE_E_Y = 480;
inline constexpr u16 CUBEMAP_SUNRISE_E_SZ = 32;

inline constexpr u16 CUBEMAP_SUNRISE_T_X = 464;
inline constexpr u16 CUBEMAP_SUNRISE_T_Y = 482;
inline constexpr u16 CUBEMAP_SUNRISE_T_SZ = 1;

inline constexpr u16 CUBEMAP_SUNRISE_B_X = 464;
inline constexpr u16 CUBEMAP_SUNRISE_B_Y = 510;
inline constexpr u16 CUBEMAP_SUNRISE_B_SZ = 1;

inline constexpr u16 CUBEMAP_SUNSET_N_X = 416;
inline constexpr u16 CUBEMAP_SUNSET_N_Y = 480;
inline constexpr u16 CUBEMAP_SUNSET_N_SZ = 32;

inline constexpr u16 CUBEMAP_SUNSET_S_X = 416;
inline constexpr u16 CUBEMAP_SUNSET_S_Y = 480;
inline constexpr u16 CUBEMAP_SUNSET_S_SZ = 32;

inline constexpr u16 CUBEMAP_SUNSET_W_X = 416;
inline constexpr u16 CUBEMAP_SUNSET_W_Y = 480;
inline constexpr u16 CUBEMAP_SUNSET_W_SZ = 32;

inline constexpr u16 CUBEMAP_SUNSET_E_X = 416;
inline constexpr u16 CUBEMAP_SUNSET_E_Y = 480;
inline constexpr u16 CUBEMAP_SUNSET_E_SZ = 32;

inline constexpr u16 CUBEMAP_SUNSET_T_X = 432;
inline constexpr u16 CUBEMAP_SUNSET_T_Y = 482;
inline constexpr u16 CUBEMAP_SUNSET_T_SZ = 1;

inline constexpr u16 CUBEMAP_SUNSET_B_X = 432;
inline constexpr u16 CUBEMAP_SUNSET_B_Y = 510;
inline constexpr u16 CUBEMAP_SUNSET_B_SZ = 1;

inline constexpr u16 CUBEMAP_SUNRISE_EFFECT_S_X = 384;
inline constexpr u16 CUBEMAP_SUNRISE_EFFECT_S_Y = 480;
inline constexpr u16 CUBEMAP_SUNRISE_EFFECT_S_SZ = 32;

inline constexpr u16 CUBEMAP_SUNRISE_EFFECT_N_X = 352;
inline constexpr u16 CUBEMAP_SUNRISE_EFFECT_N_Y = 480;
inline constexpr u16 CUBEMAP_SUNRISE_EFFECT_N_SZ = 32;

inline constexpr u16 CUBEMAP_SUNRISE_EFFECT_E_X = 320;
inline constexpr u16 CUBEMAP_SUNRISE_EFFECT_E_Y = 480;
inline constexpr u16 CUBEMAP_SUNRISE_EFFECT_E_SZ = 32;

inline constexpr u16 CUBEMAP_SUNRISE_EFFECT_T_X = 336;
inline constexpr u16 CUBEMAP_SUNRISE_EFFECT_T_Y = 510;
inline constexpr u16 CUBEMAP_SUNRISE_EFFECT_T_SZ = 1;

inline constexpr u16 CUBEMAP_SUNRISE_EFFECT_B_X = 336;
inline constexpr u16 CUBEMAP_SUNRISE_EFFECT_B_Y = 510;
inline constexpr u16 CUBEMAP_SUNRISE_EFFECT_B_SZ = 1;

inline constexpr u16 CUBEMAP_SUNRISE_EFFECT_W_X = 336;
inline constexpr u16 CUBEMAP_SUNRISE_EFFECT_W_Y = 510;
inline constexpr u16 CUBEMAP_SUNRISE_EFFECT_W_SZ = 1;

inline constexpr u16 CUBEMAP_SUNSET_EFFECT_S_X = 288;
inline constexpr u16 CUBEMAP_SUNSET_EFFECT_S_Y = 480;
inline constexpr u16 CUBEMAP_SUNSET_EFFECT_S_SZ = 32;

inline constexpr u16 CUBEMAP_SUNSET_EFFECT_N_X = 256;
inline constexpr u16 CUBEMAP_SUNSET_EFFECT_N_Y = 480;
inline constexpr u16 CUBEMAP_SUNSET_EFFECT_N_SZ = 32;

inline constexpr u16 CUBEMAP_SUNSET_EFFECT_W_X = 480;
inline constexpr u16 CUBEMAP_SUNSET_EFFECT_W_Y = 448;
inline constexpr u16 CUBEMAP_SUNSET_EFFECT_W_SZ = 32;

inline constexpr u16 CUBEMAP_SUNSET_EFFECT_T_X = 496;
inline constexpr u16 CUBEMAP_SUNSET_EFFECT_T_Y = 478;
inline constexpr u16 CUBEMAP_SUNSET_EFFECT_T_SZ = 1;

inline constexpr u16 CUBEMAP_SUNSET_EFFECT_B_X = 496;
inline constexpr u16 CUBEMAP_SUNSET_EFFECT_B_Y = 478;
inline constexpr u16 CUBEMAP_SUNSET_EFFECT_B_SZ = 1;

inline constexpr u16 CUBEMAP_SUNSET_EFFECT_E_X = 496;
inline constexpr u16 CUBEMAP_SUNSET_EFFECT_E_Y = 478;
inline constexpr u16 CUBEMAP_SUNSET_EFFECT_E_SZ = 1;


