#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Exports the texture data to a C++ file.
"""

import cv2
import numpy as np
import os
import sys


def export(x, sz=16):
    ix = iter(x)
    s = next(ix)

    for n, i in enumerate(ix):
        if (n + 1) % sz == 0:
            s += ',\n    '
        else:
            s += ', '
        s += i
    return s


def read_color(file: str) -> str:
    x = []
    y = 0

    img = cv2.imread(file, cv2.IMREAD_UNCHANGED)
    img = cv2.cvtColor(img, cv2.COLOR_BGRA2RGBA)
    raw = img.tobytes()

    for i in range(0, len(raw), 4):
        x.append('{ ' + ', '.join(map(lambda v: f"0x{v:02X}", raw[i:i + 4])) + ' }')
        y += 1

    assert len(x) == 4096
    return export(x, 4)


def generate(files: tuple[str], src: str, inc: str):
    """
    Exports the texture data to a C++ file.

    Args:
        files: the files to process
        src: the output C++ file
        inc: the output header file
    """

    payload_src = f"""
// DO NOT EDIT: AUTOGENERATED FILE (by assets/gennerators/textures.embed.py, called from CMakeLists.txt)
#include "engine/render/assets.h"

"""

    payload_inc = f"""
// DO NOT EDIT: AUTOGENERATED FILE (by assets/gennerators/textures.embed.py, called from CMakeLists.txt)
#pragma once

#include <gccore.h>

"""

    for file in files:
        name = os.path.basename(file)
        fname = name.split('.')[1]  # take YYY of XXX.YYY.ZZZ

        if name.startswith("palette"):
            payload_src += f"const GXColor {fname}Light[] ATTRIBUTE_ALIGN(32) = {{\n    {read_color(file)}}};\n\n"
            payload_inc += f"extern const GXColor {fname}Light[] ATTRIBUTE_ALIGN(32);\n"

        elif name.endswith(".tpl"):
            with open(file, "rb") as f:
                r = f.read()

            sz = len(r)
            dt = export(map(lambda x: f"0x{x:02X}", r))

            payload_src += f"const u8 {fname}TextureData[] ATTRIBUTE_ALIGN(32) = {{\n    {dt}\n}};\n\n"
            payload_inc += f"extern const u8 {fname}TextureData[] ATTRIBUTE_ALIGN(32);\n"
            payload_src += f"const u32 {fname}TextureSize = 0x{sz:08X};\n"
            payload_inc += f"extern const u32 {fname}TextureSize;\n"

            try: os.remove(file.replace(".tpl", ".h"))
            except FileNotFoundError: pass

        elif name.endswith(".h"):
            with open(file, "r") as f:
                payload_inc += f.read() + "\n"

        else:
            raise ValueError(f"unknown file type: {file}")

    with open(src, "w") as f:
        f.write(payload_src)

    with open(inc, "w") as f:
        f.write(payload_inc)


if __name__ == "__main__":
    _, *files, src, inc = sys.argv
    generate(files, src, inc)
