//
// Created by Natha on 19/02/2024.
//

#include "item.h"

bool Item::equals(Item item) const {
    return item.id == id;
}

Item::Item(int id) : id(id) {}

std::vector<Item> Item::itemList = {
        Item(BlockType::Air),
        Item(BlockType::Bedrock),
        Item(BlockType::Andesite),
        Item(BlockType::SandStone),
        Item(BlockType::CoalOre),
        Item(BlockType::CopperOre),
        Item(BlockType::DiamondOre),
        Item(BlockType::EmeraldOre),
        Item(BlockType::GoldOre),
        Item(BlockType::IronOre),
        Item(BlockType::LapisOre),
        Item(BlockType::RedstoneOre),
        Item(BlockType::Ametyst),
        Item(BlockType::Granite),
        Item(BlockType::Diorite),
        Item(BlockType::Clay),
        Item(BlockType::ClayWhite),
        Item(BlockType::ClayBrown),
        Item(BlockType::ClayBlack),
        Item(BlockType::ClayGray),
        Item(BlockType::ClayYellow),
        Item(BlockType::ClayRed),
        Item(BlockType::ClayLightGray),
        Item(BlockType::ClayPurple),
        Item(BlockType::ClayGreen),
        Item(BlockType::Dirt),
        Item(BlockType::Sand),
        Item(BlockType::RedSand),
        Item(BlockType::Gravel),
        Item(BlockType::GrassSavanna),
        Item(BlockType::GrassTemperate),
        Item(BlockType::GrassJungle),
        Item(BlockType::GrassTaiga),
        Item(BlockType::GrassDark),
        Item(BlockType::GrassCold),
        Item(BlockType::GrassSakura),
        Item(BlockType::GrassBadland),
        Item(BlockType::GrassPodzol),
        Item(BlockType::GrassSnow),
        Item(BlockType::LeaveMushroomRed),
        Item(BlockType::LeaveMushroomBrown),
        Item(BlockType::WoodAcacia),
        Item(BlockType::WoodOak),
        Item(BlockType::WoodJungle),
        Item(BlockType::WoodSpruce),
        Item(BlockType::WoodDark),
        Item(BlockType::WoodBirch),
        Item(BlockType::WoodSakura),
        Item(BlockType::WoodMushroom),
        Item(BlockType::PlankAcacia),
        Item(BlockType::PlankOak),
        Item(BlockType::PlankJungle),
        Item(BlockType::PlankSpruce),
        Item(BlockType::PlankDark),
        Item(BlockType::PlankBirch),
        Item(BlockType::PlankSakura),
        Item(BlockType::Furnace),
        Item(BlockType::CraftingTable),
        Item(BlockType::BrickStone),
        Item(BlockType::BrickDark),
        Item(BlockType::BrickRed),
        Item(BlockType::CoalBlock),
        Item(BlockType::CopperBlock),
        Item(BlockType::DiamondBlock),
        Item(BlockType::EmeraldBlock),
        Item(BlockType::GoldBlock),
        Item(BlockType::IronBlock),
        Item(BlockType::LapisBlock),
        Item(BlockType::RedstoneBlock),
        Item(BlockType::ShroomLight),
        Item(BlockType::RedstoneLamp),
        Item(BlockType::BlueIce),
        Item(BlockType::StdIce),
        Item(BlockType::Lava),
        Item(BlockType::Netherrack),
        Item(BlockType::QuartzOre),
        Item(BlockType::MagmaBlock1),
        Item(BlockType::MagmaBlock2),
        Item(BlockType::MagmaBlock3),
        Item(BlockType::Trinitrotoluene),
        Item(BlockType::QuartzBlock),
        Item(BlockType::Glowstone),
        Item(BlockType::Impostor),
        Item(BlockType::Cactus),
        Item(BlockType::LeaveAcacia),
        Item(BlockType::LeaveOak),
        Item(BlockType::LeaveJungle),
        Item(BlockType::LeaveSpruce),
        Item(BlockType::LeaveDark),
        Item(BlockType::LeaveBirch),
        Item(BlockType::LeaveSakura),
        Item(BlockType::LeaveSnow),
        Item(BlockType::Glass),
        Item(BlockType::ClearIce),
        Item(BlockType::Water)

};
